### ISSUE TITLE
Not compatible with your operating system or architecture

### ISSUE THREAD

**Issue by MVoz** [rauchg/clif#6]
Linux ubuntu 4.2.0-35-lowlatency #40-Ubuntu SMP PREEMPT Tue Mar 15 23:25:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.10

**Comment by gabmontes** [comment]
Unfortunately fsevents is an OS X-only package.
